### ISSUE TITLE
pyo3_asyncio.RustPanic: rust future panicked

### ISSUE THREAD

**Issue by chloechow** [nexus-stc/stc#1]
Hi,

Thanks for creating such powerful creative tool. 
I followed [the post](https://www.reddit.com/r/scihub/comments/12zhh5j/stc_api_interplanetary_api_for_retrieving_papers/) on Reddit to use the STC. 

I can download a file successfully with this command last week:
`stc-tools - download doi:10.1177/1745691612459058 file.pdf`

But today, I failed to run it and got `pyo3_asyncio.RustPanic: rust future panicked` error.
```
(stc) PS E:\> stc-tools - download doi:10.1177/1745691612459058 file.pdf
INFO: Setting up indices: /ipns/standard-template-construct.org/data/nexus_science/...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Tantivy(IoError(Custom { kind: Other, error: "Unsuported dictionary version, expected 1, found 0" }))', summa-embed-py\src\lib.rs:84:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\conda\miniconda3\envs\stc\Scripts\stc-tools.exe\__main__.py", line 7, in <module>
  File "E:\conda\miniconda3\envs\stc\Lib\site-packages\stc_tools\cli.py", line 94, in main
    fire.Fire(stc_tools_cli, name='stc-tools')
  File "E:\conda\miniconda3\envs\stc\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\conda\miniconda3\envs\stc\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "E:\conda\miniconda3\envs\stc\Lib\site-packages\fire\core.py", line 689, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\conda\miniconda3\envs\stc\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\conda\miniconda3\envs\stc\Lib\site-packages\stc_tools\cli.py", line 64, in download
    results = await self.search(query, index_name=index_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\conda\miniconda3\envs\stc\Lib\site-packages\stc_tools\cli.py", line 43, in search
    await self.setup()
  File "E:\conda\miniconda3\envs\stc\Lib\site-packages\stc_tools\client.py", line 38, in setup
    description = await self.index_registry.add({'config': {'remote': {
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_asyncio.RustPanic: rust future panicked
```

Environment

- OS: Windows 10
- stc-tools version: 1.0.10

**Comment by the-superpirate** [comment]
Hi, @chloechow! The development moved further last days a lot. I have updated Reddit post, could you reproduce the issue with the actual commands from https://github.com/nexus-stc/stc/tree/master/geck ? Pay an attention that the name of package has been changed as well as the command itself.

**Comment by the-superpirate** [comment]
Feel free to re-open if the issue remains

**Comment by chloechow** [comment]
The newer version 1.4.4 works on my Linux machine, thanks.

**Comment by isaldiviagonzatti** [comment]
Hi, 

I got the pyo3_asyncio.RustPanic: rust future panicked error on my Linux machine using the commands in https://github.com/nexus-stc/stc/tree/master/geck and after installing IPFS and stc-geck a month ago.

Linux Mint 21.2 Victoria
sct-geck version 1.8.38

```geck - serve
INFO: Setting up indices...
thread 'tokio-runtime-worker' panicked at /home/runner/work/summa/summa/summa-core/src/directories/network_directory.rs:78:23:
HyperError(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/ignacio/miniconda3/envs/downSci/bin/geck", line 8, in <module>
    sys.exit(main())
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/stc_geck/cli.py", line 238, in main
    fire.Fire(stc_geck_cli, name='geck')
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/fire/core.py", line 689, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/stc_geck/cli.py", line 25, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/stc_geck/cli.py", line 176, in serve
    async with self.geck:
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/aiokit/aiothing.py", line 81, in __aenter__
    await self.start()
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/aiokit/aiothing.py", line 39, in guarded_fn
    r = await fn(*args, **kwargs)
  File "/home/ignacio/miniconda3/envs/downSci/lib/python3.8/site-packages/stc_geck/client.py", line 166, in start
    await self.summa_embed_server.start()
pyo3_asyncio.RustPanic: rust future panicked
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbcf3866ac0>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbcf3866c10>
```

**Comment by Red-Skuller** [comment]
use summa_embed version 0.22.4
It doesn't work with the latest summa_embed
